### ISSUE TITLE
Protoo is a real peer to peer server and client?

### ISSUE THREAD

**Issue by Varooneh** [versatica/protoo#13]
Hi,
I've question. 
is ```Protoo library``` a real peer to peer server and client? 
Can use part of enterprise application?
Can connect to protoo server from C#, Delphi, Java or etc...?

Thank you.

**Comment by ibc** [comment]
Currently there is just a protoo server component (for Node.js) and a protoo client component (in JS for browser and Node.js).

Having protoo client in other languages is a nice to have feature, but there are not. PR welcome.
