### ISSUE TITLE
prooto-client - ability to disable node-retry

### ISSUE THREAD

**Issue by aetheon** [versatica/protoo#15]
Hi guys,

At the moment protoo-client always auto retries WS connections due to `wasConnected` check [here](https://github.com/versatica/protoo/blob/master/client/lib/transports/WebSocketTransport.js#L147).

The only way around this is to try to set `_closed` true [here](https://github.com/versatica/protoo/blob/master/client/lib/transports/WebSocketTransport.js#L164).

Would you guys willing to accepts PRs to disable the usage of node-retry when creating WebSocketTransport?

The main reason is that for code maintenance, using event callback events can become hard to maintain. An example is when a mediasoup transport fails when connecting to a VPN during a call and the WS keeps the connection alive.

Tks.

**Comment by ibc** [comment]
Why don't you call close() instead and create a new Peer later when ready?

**Comment by aetheon** [comment]
@ibc ya sorry missed that part. Calling `close()` doesn't close the WS server side, the server eventually picks it up using `websocket` package nodejs setTimeouts.

```
keepalive: true,
keepaliveInterval : 60000
```

If a WS request is created that removes the peer connection, the client always retries due to wasConnected check mentioned above.

**Comment by ibc** [comment]
> @ibc ya sorry missed that part. Calling `close()` doesn't close the WS server side, the server eventually picks it up using `websocket` package nodejs setTimeouts.

I don't understand what you mean, sorry. Calling `close()` in client side will close the WS in server side as far as the WS was connected.

> If a WS request is created that removes the peer connection, the client always retries due to wasConnected check mentioned above.

There is no PeerConnection in protoo, nor its behavior depends on any PeerConnection handled by the app or another library. I don't really get your point here.

**Comment by aetheon** [comment]
You can try it with mediasoup-demo pretty sure it happens there.

When calling `client.close()` the close event [here](https://github.com/versatica/mediasoup-demo/blob/v3/server/lib/Room.js#L246).

The reason is in websocket [here](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketConnection.js#L111) and [here](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketConnection.js#L119).

**Comment by ibc** [comment]
Sorry, the reason of what? I still don't understand the purpose of this issue or the problem it describes.

**Comment by aetheon** [comment]
> Sorry, the reason of what? I still don't understand the purpose of this issue or the problem it describes.

> > Would you guys willing to accepts PRs to disable the usage of node-retry when creating WebSocketTransport?

Basically would you accept a flag to disable the usage of node-retry in protoo-client.

Can't explain the problem any better - https://github.com/versatica/protoo/issues/15#issuecomment-619970780

**Comment by ibc** [comment]
The `retry` option of protoo `Peer` is configurable. Isn't that valid enough? You can disable retry behavior with proper settings into `retry` option.

> Can't explain the problem any better 

I do need to understand the issue in order to have an opinion about it.

**Comment by aetheon** [comment]
This is my workaround that avoid WS reconnect when `leave` request closes the connection in server-side. I would love to avoid this and create a PR to disable auto retry in protoo-client.

```
client._transport._ws.onclose = null;
const response = client.request('leave');
client.close();
```

**Comment by ibc** [comment]
There is no `leave` request in protoo.

1. If you call `peer.close()` in client while the connection was open, the server side WS will also be closed.
2. If you want to close the WS server side and avoid client side reconnection attempts, you can
  2.1. Close the server side `peer` with WS reason 4000, so client won't try to reconnect.
  2.2. Send a protoo notification to the client (i.e. `closed`) so the client app will call `peer.close()`.

I've never had the problem you describe above, so I'm pretty sure that we do not need any hack to disable auto-retry in protoo client side.

Now, if you don't agree with numeric bullets above, please explain exactly why. And let's try to not reference stuff related to mediasoup or PeerConnection. protoo is a separate library that does not depend on mediasoup or WebRTC at all.

**Comment by aetheon** [comment]
The `leave` in the example above is a request that removes the peers and disposes if its connection, not a protoo api.

> Close the server side peer with WS reason 4000, so client won't try to reconnect.
👍 Will give that a shoot tks.

> And let's try to not reference stuff related to mediasoup or PeerConnection.
Its kind of impossible to describe the issue without showing the trace of what is happening with the relying libs.

Tks again.

**Comment by ibc** [comment]
> Its kind of impossible to describe the issue without showing the trace of what is happening with the relying libs.

I understand, but I need to focus to understand the problem. Anyway, as you can figure out I use protoo + mediasoup-client extensively and never got into that issue, that's why I insist in looking for ab already existing different approach.

**Comment by aetheon** [comment]
The main issue is that when connecting to a VPN when in a call the receiver(producer)Transport disconnects and other people loose the video/audio with that peer.

The client app could restart it but the callback logic become very hard to maintain, so the app just resets itself and just one loading code path to simplify.

I can see this issue on mediasoup-demo. Sure I know the demo is just a demo not a full product.

**Comment by ibc** [comment]
First, if the WebRTC transports "disconnects" it can still become "connected" alone. If its state becomes "failed", then no.  In the former case you don't need to do anything but wait. In the latter you have a problem and may need to restart the transport (`transport.restartIce()`).

If the WS disconnects then you have have to reset all your WebRTC status anyway.
