### ISSUE TITLE
When using protoo WebSocket in nodejs server project can I use any WebSocket client?

### ISSUE THREAD

**Issue by xplatsolutions** [versatica/protoo#19]
I am using this server-side in nodejs project and trying to connect from iOS client using [Starscream](https://github.com/daltoniam/Starscream) but receiving `protoo-server:WARN:WebSocketServer _onRequest() | invalid/missing Sec-WebSocket-Protocol`.

I just want to confirm that there is no limitation where I can't connect from non-protoo client.

**Comment by xplatsolutions** [comment]
From my iOS client, I used the below code to setup the handshake request.

```
var request = URLRequest(url: URL(string: wsUri)!)
request.setValue("chat,superchat,chatmessage", forHTTPHeaderField: "Sec-WebSocket-Protocol")
    // Allow self-signed certificates
    // Load certificates and public keys into an app bundle, use the builtin pinner and TrustKit.
    let pinner = FoundationSecurity(allowSelfSigned: true) // don't validate SSL certificates
    self.socket = WebSocket.init(request: request, certPinner: pinner)
    // Handle socket delegate methods on the global thread (semaphor will lock if not set to global..)
    self.socket!.callbackQueue = DispatchQueue.global()
    self.socket!.delegate = self
    self.socket!.connect()
```

I am not really sure the `Sec-WebSocket-Protocol` value needed for the protoo server. Have in mind that I use code from the [mediasoup-demo](https://github.com/versatica/mediasoup-demo)

**Comment by xplatsolutions** [comment]
I found in the source code that is needed to set as `protoo` after setting the `request.setValue("protoo", forHTTPHeaderField: "Sec-WebSocket-Protocol")` it worked

**Comment by ibc** [comment]
Exactly.
