### ISSUE TITLE
Peer disconnects randomly and reconnects afterwards

### ISSUE THREAD

**Issue by razorxan** [versatica/protoo#21]
I just started trying protoo and got random disconnect/reconnect (close/open) events fired on the client peer (same on the server side peer). Just trying to figure out if it's something I'm missing out or it's just a bug.

My client side app strongly relies on the peer "open" event, which as i said, fires multiple times because of the random "reconnection" behaviour.

If you don't know what im talking about I'll provide you with the code I'm using.
This is my console atm.

![protoo-wtf](https://user-images.githubusercontent.com/715859/99950214-7d851380-2d7c-11eb-8c51-e853e04a60b0.png)

Have I missed some configuration?

Thank you very much for your work.

**Comment by ibc** [comment]
No idea, sorry, but if this was a bug we would be aware of it. It's not a  bug but something happening in your app. I'm afraid I cannot give support about this, sorry.

**Comment by razorxan** [comment]
just as an additional piece of information: if I setInterval notify "something" every x seconds, the problem does not occur.
Seems like the keepalive interval is not sent by default by the peers.

**Comment by ibc** [comment]
You can set keepalive options by passing the corresponding settings to the `WebSocketServer` constructor:

https://protoojs.org/#websocketserver
