### ISSUE TITLE
Protoo request unable to send Map.

### ISSUE THREAD

**Issue by ritvij14** [versatica/protoo#27]
I am trying to send a Map as a part of an object from protoo request from frontend, to the backend where protoo request is being handled, but on logging the data on backend, the map being received inside the object is empty.

Other fields come fine, which are String and int types.

**Comment by ibc** [comment]
You cannot send a Map but just JSON serializable data. This is not a limitation of protoo, the same would happen if you try to attach a Map or whatever complex struct into a HTTP POST.
